### ISSUE TITLE
Feature request: add --quiet flag

### ISSUE THREAD

**Issue by ez-me** [sstadick/crabz#28]
I wanted to pipe the output from ```crabz``` to another program, and noticed it always adds a header to the output.

It would be nice for ```crabz``` to detect if it's not running interactively, or at least have the ```--quiet``` flag.

**Comment by sstadick** [comment]
This would be nice! PRs very welcome, I'm not sure I'll be adding that myself anytime soon.

**Comment by sstadick** [comment]
See v0.9.0
