### ISSUE TITLE
`--version` doesn't print version info

### ISSUE THREAD

**Issue by coolaj86** [sstadick/crabz#31]
On a fresh download of `crabz@0.8.1` on Linux:

```sh
crabz -V
```

```text
crabz git:22d81b5
```

FYI, the standard git commit reference is just a `g` prefix and then 7 characters: `g22d81b5`.

Often like this:

```text
crabz v0.8.1 (g22d81b5)
```

The reason it's formatted that way comes from `git-describe`, which is typically used by tools that mix git commit info with other baked-in build / release info.

**Comment by camlloyd** [comment]
@coolaj86 How are you installing `crabz`, from a clone or a fork of this repo? `git-describe` needs to be able to find tags.
the `git:` prefix helps distinguish that the version is sourced from `git` vs. `cargo`.

### fork:
```
crabz git:23b5016
```

### clone:
```
crabz git:v0.8.1-2-g23b5016
```

### cargo:
```
crabz cargo:0.8.1
```

**Comment by sstadick** [comment]
Thanks for checking this @camlloyd. Closing. @coolaj86 feel free to reopen if needed.
