### ISSUE TITLE
0.9.0 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [sstadick/crabz#35]
👋 it looks like 0.9.0 release was not completed (due to action run failure, https://github.com/sstadick/crabz/actions/runs/8317134736/job/22757518845), ie the release was not created. Raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/166472

cc @sstadick

**Comment by sstadick** [comment]
Thanks for making the issue! I had missed that. Fixing now.

**Comment by sstadick** [comment]
See v0.9.1 (CI in progress now, I'll watch it this time)

**Comment by chenrui333** [comment]
Cool, cool, thanks!
